# Generated by Django 4.0.3 on 2022-05-13 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='contenido',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='titulo',
            new_name='mascota',
        ),
    ]
