# Generated by Django 4.0.3 on 2022-05-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_rename_contenido_servicio_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='disponibilidad',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(upload_to='servicios'),
        ),
    ]
