# Generated by Django 4.0.3 on 2022-05-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0003_servicio_disponibilidad_alter_servicio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='adoptante',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='alguna_enfermedad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='alimentacion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='edad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='raza',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
