# Generated by Django 4.0.3 on 2022-05-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nuevos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alimentacion', models.CharField(max_length=50)),
                ('Vacunacion', models.CharField(max_length=50)),
                ('Edad', models.CharField(max_length=10)),
                ('Género', models.CharField(max_length=20)),
                ('Nombre', models.CharField(max_length=50)),
                ('Fecha_de_rescate', models.CharField(max_length=10)),
                ('Adoptante', models.CharField(max_length=20)),
                ('Raza', models.CharField(max_length=20)),
                ('Alguna_Enfermedad', models.CharField(max_length=100)),
            ],
        ),
    ]
