# Generated by Django 4.0.3 on 2022-05-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adopciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Edad', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=8)),
                ('Domicilio', models.CharField(max_length=50)),
                ('Numero_de_mascotas', models.CharField(max_length=10)),
                ('Razones_para_adoptar', models.CharField(max_length=100)),
            ],
        ),
    ]
